<div class="page-header-inner ">
  <div class="navbar-header">
    <a href="?page=gsupport" class="navbar-brand">
    <img src="<?php echo GSPL_URL . 'assets/images/gs.png'; ?>" alt="genesis supporter" />
    </a>
  </div>
  <div class="top-menu">
    <ul class="nav navbar-nav pull-right">
      <li class="contact-item">
        <a target="_blank" href="https://github.com/duyngha/genesis-supporter/issues" title="Ask me">
          <i class="icon-question icons"></i>
        </a>
      </li>
    </ul>
  </div>
</div>